### ISSUE TITLE
Two logouts issued when only one logout() executed.

### ISSUE THREAD

**Issue by open4storage** [EMCECS/python-ecsclient#29]
I am using a single logout() command, but the requests sent by the code I see two been issued.  The problem is the first one succeed (200) and the second call fails (probably because the first 200).

**Comment by open4storage** [comment]
```DEBUG:requests.packages.urllib3.connectionpool:"GET /user/whoami HTTP/1.1" 200 None
DEBUG:ecsclient.common.token_request:Token validated successfully
DEBUG:requests.packages.urllib3.connectionpool:"GET /logout HTTP/1.1" 200 None
DEBUG:ecsclient.baseclient:Removing cached token 'temp.txt'
DEBUG:root:Saved data to disk...
DEBUG:requests.packages.urllib3.connectionpool:"GET /logout HTTP/1.1" 401 None
ERROR:ecsclient.baseclient:Status code NOT OK
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./account_endpoint.py", line 51, in run
    user_dict = self.ecsc.get_user_consumption()
  File "/home/julio/projects/ecs-account-usage/src/account_usage.py", line 76, in get_user_consumption
    client.authentication.logout()
  File "/home/julio/.local/lib/python3.5/site-packages/ecsclient/authentication.py", line 35, in logout
    logout_resp = self.conn.get('logout')
  File "/home/julio/.local/lib/python3.5/site-packages/ecsclient/baseclient.py", line 108, in get
    return self._request(url, params=params)
  File "/home/julio/.local/lib/python3.5/site-packages/ecsclient/baseclient.py", line 160, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Token not found or invalid token provided - Invalid credentials or authentication token provided to access to this resource: https://portal.ecstestdrive.com/logout 401 Unauthorized  [first 60 chars of response] {"code":4000,"retryable":false,"description":"Invalid creden
```
It also doesnt seem like logout remove the old token file.  Causing a failure on the next login as the code finds it and try to use it.
