### ISSUE TITLE
Error when creating a data store in ECS 3.1

### ISSUE THREAD

**Issue by adrianmo** [EMCECS/python-ecsclient#43]
The API has changed in 3.1 and it fails to create data store given an IP address. It should instead use a node ID.

Error output:
```
> Adding Data Stores to Storage Pool:
>       vdc1/sp1/192.168.2.220
Traceback (most recent call last):
  File "/usr/local/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.4.0', 'console_scripts', 'ecsconfig')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/ecsconfig.py", line 637, in sp
    tasks = add_all()
  File "/usr/local/bin/ecsconfig.py", line 613, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/local/bin/ecsconfig.py", line 605, in add_one
    sp_tasks.append(sp_add_node(sp_id, node))
  File "/usr/local/bin/ecsconfig.py", line 582, in sp_add_node
    return conf.api_client.data_store.create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/ecsclient/common/provisioning/data_store.py", line 217, in create
    return self.conn.post('vdc/data-stores/commodity', json_payload=payload)
  File "/usr/local/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/local/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Usage of node IP address in place of nodeId is no longer supported - Api Parameter Node Id Invalid: https://192.168.2.220:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1050,"retryable":false,"description":"Api Parameter
```

**Comment by adrianmo** [comment]
3.1 API specs: http://doc.isilon.com/ECS/3.1/API/index.html

**Comment by adrianmo** [comment]
After examining the new API, it looks like we need to make a previous call to the Node endpoint to obtain the Node IDs of all members of the cluster. Then use those IDs to create the data stores. This means that this issue is blocked until we implement support for the Node endpoint.

**Comment by adrianmo** [comment]
Also, as breaking changes have (again) been introduced to the new API and it's highly likely to happen again in the future, it has come the time to implement a clever way to determine the target ECS version and instantiate the proper client.

**Comment by adrianmo** [comment]
This issue is blocked by #47

**Comment by adrianmo** [comment]
Fixed.
